const providers = [
  {
    "providerName": "Lisa Landry",
    "photo": "images/lisa-landry.jpg",
    "serviceType": "Therapy",
    "acceptingNewClients": true,
    "inPerson": false,
    "online": true,
    "weekdayDaytime": true,
    "weekdayEvening": false,
    "weekend": false,
    "flexible": false,
    "children": false,
    "teens": false,
    "adults": true,
    "couples": false,
    "families": false,
    "aetna": true,
    "bcbstx": true,
    "uhc": true,
    "privatePay": true,
    "concerns": [
      "PTSD",
      "Trauma",
      "ADHD",
      "Depression",
      "Anxiety",
      "LGBTQ+",
      "Grief",
      "Gender Identity",
      "Women's Issues",
      "Burnout"
    ],
    "treatments": [
      "Trauma-Informed Therapy",
      "Somatic Approaches",
      "PolyVagal Therapy",
      "Mindfulness/Meditation",
      "Client Focused Therapy",
      "Attachment Based Therapy"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/lisa-landry",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "Lisa has 22+ years experience and specializes in trauma-informed care for adults navigating anxiety, identity concerns, and life transitions"
  },
  {
    "providerName": "Russell Payne",
    "photo": "images/russell-payne.jpg",
    "serviceType": "Therapy",
    "acceptingNewClients": true,
    "inPerson": true,
    "online": true,
    "weekdayDaytime": true,
    "weekdayEvening": true,
    "weekend": false,
    "flexible": true,
    "children": true,
    "teens": true,
    "adults": true,
    "couples": true,
    "families": false,
    "aetna": true,
    "bcbstx": true,
    "uhc": true,
    "privatePay": true,
    "concerns": [
      "Spiritual Counseling",
      "Couples Counseling",
      "ADHD",
      "Grief",
      "Men's Issues",
      "Anxiety",
      "Depression",
      "Burnout"
    ],
    "treatments": [
      "CBT",
      "DBT",
      "Talk",
      "Christian Counseling"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/russell-payne",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "Russell sees children, adolescents, and adults and specializes in spectrum disorders, ADHD, behavioral issues, couples counseling, and spiritual counseling."
  },
  {
    "providerName": "Tina Herrera",
    "photo": "images/tina-herrera.jpg",
    "serviceType": "Therapy",
    "acceptingNewClients": true,
    "inPerson": true,
    "online": true,
    "weekdayDaytime": false,
    "weekdayEvening": true,
    "weekend": false,
    "flexible": true,
    "children": true,
    "teens": true,
    "adults": true,
    "couples": true,
    "families": true,
    "aetna": true,
    "bcbstx": true,
    "uhc": true,
    "privatePay": true,
    "concerns": [
      "Divorce",
      "Grief",
      "Family Counseling",
      "Parent/Child Conflict",
      "Couples Counseling",
      "Behavior Counseling",
      "Anxiety",
      "Depression",
      "Burnout"
    ],
    "treatments": [
      "CBT",
      "DBT",
      "Talk"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/tina-herrera",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "Tina sees children, adolescents and adults, teens struggling with anxiety and depression, and specializes in grief, divorce and behavioral issues, and adults with trauma, anxiety and depression, and family counseling and marriage counseling. "
  },
  {
    "providerName": "Natasha Lovett",
    "photo": "images/natasha-lovett.jpg",
    "serviceType": "Therapy",
    "acceptingNewClients": true,
    "inPerson": false,
    "online": true,
    "weekdayDaytime": false,
    "weekdayEvening": true,
    "weekend": true,
    "flexible": false,
    "children": false,
    "teens": true,
    "adults": true,
    "couples": false,
    "families": true,
    "aetna": true,
    "bcbstx": true,
    "uhc": true,
    "privatePay": true,
    "concerns": [
      "Anxiety",
      "Depression",
      "Parent/Child Conflict",
      "Self-Harm",
      "Suicidal Ideation",
      "Burnout"
    ],
    "treatments": [
      "CBT",
      "DBT",
      "Talk"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/natasha-lovett",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "Natasha specializes in adolescents and adults who are struggling with anxiety and depression. Those who are having family conflicts, and individuals with self-injury behaviors and suicidal ideation. "
  },
  {
    "providerName": "Christie Greeley",
    "photo": "images/christie-greeley.jpg",
    "serviceType": "Therapy",
    "acceptingNewClients": true,
    "inPerson": false,
    "online": true,
    "weekdayDaytime": true,
    "weekdayEvening": false,
    "weekend": false,
    "flexible": false,
    "children": false,
    "teens": false,
    "adults": true,
    "couples": true,
    "families": false,
    "aetna": true,
    "bcbstx": true,
    "uhc": true,
    "privatePay": true,
    "concerns": [
      "PTSD",
      "Trauma",
      "Couples Counseling",
      "Depression",
      "Anxiety",
      "LGBTQ+",
      "Grief",
      "Gender Identity",
      "OCD",
      "Women's Issues",
      "Burnout"
    ],
    "treatments": [
      "Gottman Method",
      "CBT",
      "DBT",
      "Talk"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/christie-greeley",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "Christie specializes in trauma-informed care for adults navigating anxiety, identity concerns, life transitions, and couples/marriage counseling."
  },
  {
    "providerName": "Rhonda Polakoff",
    "photo": "images/rhonda-polakoff.jpg",
    "serviceType": "Psychological Evaluation",
    "acceptingNewClients": true,
    "inPerson": false,
    "online": true,
    "weekdayDaytime": true,
    "weekdayEvening": false,
    "weekend": false,
    "flexible": false,
    "children": true,
    "teens": true,
    "adults": true,
    "couples": false,
    "families": false,
    "aetna": false,
    "bcbstx": false,
    "uhc": false,
    "privatePay": true,
    "concerns": [
      "Psychological Evaluations",
      "Spectrum Disorders",
      "ADHD",
      "Behavior Counseling",
      "Learning Differences",
      "Gifted & Talented",
      "Trauma"
    ],
    "treatments": [
      "Psychological Evaluation"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/rhonda-polakoff",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "Dr. Polakoff helps families and individuals gain clarity about ADHD, autism, learning disabilities, anxiety, depression, and other conditions that impact daily functioning."
  },
  {
    "providerName": "Jan Leger",
    "photo": "images/jan-leger.jpg",
    "serviceType": "Therapy",
    "acceptingNewClients": true,
    "inPerson": false,
    "online": true,
    "weekdayDaytime": true,
    "weekdayEvening": true,
    "weekend": true,
    "flexible": true,
    "children": false,
    "teens": true,
    "adults": true,
    "couples": false,
    "families": false,
    "aetna": true,
    "bcbstx": true,
    "uhc": true,
    "privatePay": true,
    "concerns": [
      "Depression",
      "Anxiety",
      "Substance Abuse",
      "Eating Disorders",
      "Self-Harm",
      "Trauma",
      "Divorce",
      "Life Transitions",
      "Grief",
      "Burnout"
    ],
    "treatments": [
      "Trauma-Informed Therapy",
      "CBT",
      "DBT",
      "Talk"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/jan-leger",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "Jan specializes in trauma-informed care for adolescents and adults navigating anxiety, substance abuse, eating disorders, grief, divorce, anxiety, and depression. "
  },
  {
    "providerName": "Joo Kim",
    "photo": "images/joo-kim.jpg",
    "serviceType": "Therapy",
    "acceptingNewClients": true,
    "inPerson": false,
    "online": true,
    "weekdayDaytime": true,
    "weekdayEvening": true,
    "weekend": false,
    "flexible": false,
    "children": false,
    "teens": true,
    "adults": true,
    "couples": false,
    "families": false,
    "aetna": true,
    "bcbstx": true,
    "uhc": true,
    "privatePay": true,
    "concerns": [
      "Relationships",
      "PTSD",
      "Trauma",
      "Sports Trauma",
      "Anxiety",
      "Depression",
      "Grief",
      "Spiritual Counseling",
      "Burnout"
    ],
    "treatments": [
      "Brainspotting",
      "Internal Family Systems",
      "Cognitive Behavioral Therapy",
      "Motivational Interviewing",
      "Solution Focused",
      "Person Centered",
      "Psycho-dynamic",
      "Psych Rehab"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/joo-kim",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "Joo specializes in trauma-informed care for adults navigating anxiety, depression, trauma, relational challenges and life transitions"
  },
  {
    "providerName": "Nikki Moon",
    "photo": "images/nikki-moon.jpg",
    "serviceType": "Therapy",
    "acceptingNewClients": true,
    "inPerson": true,
    "online": true,
    "weekdayDaytime": false,
    "weekdayEvening": true,
    "weekend": false,
    "flexible": false,
    "children": true,
    "teens": true,
    "adults": true,
    "couples": false,
    "families": true,
    "aetna": true,
    "bcbstx": true,
    "uhc": true,
    "privatePay": true,
    "concerns": [
      "Domestic Violence",
      "Grief",
      "Family Counseling",
      "Behavior Counseling",
      "Anxiety",
      "Depression",
      "Parent/Child Conflict",
      "Burnout"
    ],
    "treatments": [
      "CBT",
      "Mindfulness",
      "Trauma-Informed Therapy",
      "Talk"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/nikki-moon",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "Nikki specializes in helping children, adolescents, and adults overcome obstacles that may be preventing them from living full lives. "
  },
  {
    "providerName": "LaTasha Taylor",
    "photo": "images/latasha-taylor.jpg",
    "serviceType": "Therapy",
    "acceptingNewClients": true,
    "inPerson": false,
    "online": true,
    "weekdayDaytime": false,
    "weekdayEvening": false,
    "weekend": true,
    "flexible": false,
    "children": false,
    "teens": true,
    "adults": true,
    "couples": false,
    "families": true,
    "aetna": true,
    "bcbstx": true,
    "uhc": true,
    "privatePay": true,
    "concerns": [
      "PTSD",
      "Trauma",
      "BIPOC",
      "LGBTQ+",
      "Domestic Violence",
      "Grief",
      "Parenting",
      "Self-Harm",
      "Depression",
      "Anxiety",
      "Burnout"
    ],
    "treatments": [
      "CBT",
      "Trauma-Informed Therapy",
      "EMDR",
      "Narrative",
      "General Systems Theories"
    ],
    "consultationAvailable": true,
    "fullBioUrl": "https://landrytherapygroup.com/latasha-taylor",
    "appointmentFormUrl": "https://landrytherapygroup.com/contact",
    "bio": "LaTasha specializes in trauma-informed care for adults navigating trauma, self-harm, domestic violence, anxiety, identity concerns, and life transitions"
  }
];
